x-load-test-defaults: &load-test-defaults
  restart: "no"
  networks:
    - foodme_network
  environment:
    - PYTHONUNBUFFERED=1

services:
  load-test-setup:
    <<: *load-test-defaults
    image: python:3.11-slim
    container_name: foodme-load-test-setup
    working_dir: /app
    volumes:
      - load-test-cache:/root/.cache/pip
      - ../requirements.txt:/app/requirements.txt
    command: >
      bash -c "
        pip install --cache-dir /root/.cache/pip -r requirements.txt
      "

  load-test:
    <<: *load-test-defaults
    image: python:3.11-slim
    container_name: foodme-load-test
    working_dir: /app
    volumes:
      - load-test-cache:/root/.cache/pip
      - ../locustfile.py:/app/locustfile.py
      - ../requirements.txt:/app/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1
      - LOCUST_HOST=${TARGET_HOST:-http://foodme-app:3000}
      - LOCUST_USERS=${LOAD_TEST_USERS:-10}
      - LOCUST_SPAWN_RATE=${LOAD_TEST_SPAWN_RATE:-2}
      - LOCUST_RUN_TIME=${LOAD_TEST_DURATION:-600s}
      - LOCUST_HEADLESS=${LOAD_TEST_HEADLESS:-true}
    depends_on:
      - load-test-setup
    command: >
      bash -c "
        pip install --cache-dir /root/.cache/pip -r requirements.txt &&
        locust -f locustfile.py 
          --host=$$LOCUST_HOST 
          --headless=$$LOCUST_HEADLESS
          -u $$LOCUST_USERS 
          -r $$LOCUST_SPAWN_RATE 
          -t $$LOCUST_RUN_TIME
      "

volumes:
  load-test-cache:
    driver: local
    name: foodme-load-test-cache

networks:
  foodme_network:
    external: true
    name: foodme_network